[build-system]
requires = ["setuptools", "wheel", "Cython", "numpy>=1.17.3"]
build-backend = "setuptools.build_meta"

[project]
name = "scikit-surprise"
version = "1.1.3"
description = "An easy-to-use library for recommender systems."
readme = "README.md"
authors = [
    {name = "Nicolas Hug", email = "contact@nicolas-hug.com"},
]
license = { file = "LICENSE.md" }
keywords = ["recommender", "recommendation system"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "joblib >= 1.0.0",
    "numpy >= 1.17.3",
    "scipy >= 1.3.2",
]

[project.scripts]
surprise = "surprise:main"

