# This workflow will run lint.sh

name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install "black==22.6.0" "flake8==5.0.4" "usort==1.0.4"
        pip install -r requirements_dev.txt
    - name: Install Surprise
      run: |
        python -m pip install -e .  # Not sure it's needed but whatevs
    - name: Run linters and formatters
      run: |
        chmod +x lint.sh
        ./lint.sh
